[package]
name = "bondlink-wintun"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
wintun-bindings = "0.7"
windows-sys = { version = "0.59", features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_Foundation",
    "Win32_System_IO",
] }

[dev-dependencies]
